stages:
  - test
  - build

variables:
  MAVEN_CLI_OPTS: "--show-version"

cache:
  paths:
    - .m2/repository

image: ${PRIVATE_REPOSITORY_PULL}/maven:3.6.3-jdk-8

building:
  stage: build
  script:
    - mvn -s $M2_PROXY $MAVEN_CLI_OPTS package -DskipTests
  after_script:
    - mvn -s $M2_PROXY cargo:redeploy -Dcargo.remote.username=${TOMCAT_USERNAME} -Dcargo.remote.password=${TOMCAT_PASSWORD} -Dcargo.hostname=${TOMCAT_HOST} -Dcargo.servlet.port=${TOMCAT_PORT}
  only:
    - /-release/
  tags:
    - docker
  artifacts:
    paths:
      - target/*.war
    name: $CI_PROJECT_NAME-$CI_COMMIT_TAG
