stages:
    - build
    - deploy

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository

packaging:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS package'
  only:
    - /-release/
  tags:
    - docker
  artifacts:
    paths:
      - target/*.war
    name: $CI_PROJECT_NAME-$CI_COMMIT_TAG

deploy:
  # Use stage test here, so the pages job may later pickup the created site.
  stage: deploy
  script:
    - mvn cargo:redeploy -Dcargo.remote.username=${TOMCAT_USERNAME} -Dcargo.remote.password=${TOMCAT_PASSWORD} -Dcargo.hostname=${TOMCAT_HOST} -Dcargo.servlet.port=${TOMCAT_PORT}
  only:
    - /-release/
  tags:
    - docker
  artifacts:
    paths:
      - target/*.war
    name: $CI_PROJECT_NAME-$CI_COMMIT_TAG